[package]
name = "gtl-artifacts"
version = "0.1.0"
edition.workspace = true
publish.workspace = true

[dependencies]
anyhow.workspace = true
base64.workspace = true
gtl-application.workspace = true
gtl-models.workspace = true
gtl-web = { workspace = true, features = ["artifact"] }
gtl-wire.workspace = true
sha2.workspace = true

[dev-dependencies]
flate2.workspace = true
gtl-infra.workspace = true
tempfile.workspace = true

[lints]
workspace = true
