[preview]
path = "crates/gtl-web"
package = "gtl-web"
source-directories = [
  "../gtl-wire/src",
  "../gtl-parser/src",
  "../gtl-web-contracts/src",
  "dev",
  "src",
  "../../../../shared-libs/dx-preview/crates/dx-preview-macros/src",
  "../../../../shared-libs/dx-preview/crates/dx-preview/src",
]

[serve]
port = 8080
open = false

[tailwind]
input = "dev/styles/tailwind.css"
output = "assets/component-preview.css"
