[package]
name = "gtl-cli"
version = "0.1.0"
edition.workspace = true
publish.workspace = true

[[bin]]
name = "git-tools"
path = "src/main.rs"

[lib]
name = "gtl_cli"
path = "src/lib.rs"

[dependencies]
anyhow.workspace = true
clap.workspace = true
clap-cargo.workspace = true
dialoguer.workspace = true
gtl-client.workspace = true
gtl-wire = { workspace = true, features = ["grpc"] }
gtl-models.workspace = true
libc.workspace = true
serde.workspace = true
serde_json.workspace = true
thiserror.workspace = true
toml.workspace = true
tokio = { workspace = true, features = ["rt"] }

[dev-dependencies]
assert_cmd.workspace = true
gtl-local-transport.workspace = true
gtl-server.workspace = true
predicates.workspace = true
strum.workspace = true
tempfile.workspace = true
tonic.workspace = true

[target.'cfg(unix)'.dev-dependencies]
expectrl.workspace = true

[lints]
workspace = true
