[package]
name = "gtl-models"
version = "0.1.0"
edition.workspace = true
publish.workspace = true

[dependencies]
nutype = { workspace = true, features = ["serde"] }
serde.workspace = true
strum.workspace = true
thiserror.workspace = true

[dev-dependencies]
serde_json.workspace = true

[lints]
workspace = true
