[package]
name = "gtl-infra"
version = "0.1.0"
edition.workspace = true
publish.workspace = true

[dependencies]
anyhow.workspace = true
gtl-application.workspace = true
directories.workspace = true
gtl-models.workspace = true
gix.workspace = true
notify.workspace = true
parking_lot.workspace = true
rusqlite.workspace = true
rusqlite_migration.workspace = true
serde.workspace = true
serde_json.workspace = true
sha2.workspace = true
strum.workspace = true
tempfile.workspace = true
thiserror.workspace = true
tokio = { workspace = true, features = ["rt"] }
toml.workspace = true
toml_edit.workspace = true

[target.'cfg(any(target_os = "linux", target_os = "macos"))'.dependencies]
libc.workspace = true

[target.'cfg(target_os = "macos")'.dependencies]
notify = { workspace = true, features = ["macos_fsevent"] }

[dev-dependencies]
gtl-wire.workspace = true
gtl-application = { workspace = true, features = ["testing"] }

[lints]
workspace = true
