[package]
name = "gtl-client"
version = "0.1.0"
edition.workspace = true
publish.workspace = true

[dependencies]
gtl-models.workspace = true
gtl-wire.workspace = true
serde.workspace = true
thiserror.workspace = true

[target.'cfg(not(target_arch = "wasm32"))'.dependencies]
gtl-local-auth.workspace = true
gtl-wire = { workspace = true, features = ["grpc"] }
tonic = { workspace = true, features = ["router", "transport"] }
tonic-health.workspace = true

[target.'cfg(target_arch = "wasm32")'.dependencies]
serde-wasm-bindgen = { workspace = true, optional = true }
wasm-bindgen = { workspace = true, optional = true }
wasm-bindgen-futures = { workspace = true, optional = true }

[dev-dependencies]
tempfile.workspace = true
serde_json.workspace = true
tokio = { workspace = true, features = [
  "macros",
  "net",
  "rt-multi-thread",
  "sync",
  "time",
] }
tokio-stream = { workspace = true, features = ["net"] }

[lints]
workspace = true

[features]
viewer-ipc = [
  "dep:serde-wasm-bindgen",
  "dep:wasm-bindgen",
  "dep:wasm-bindgen-futures",
]
