[package]
name = "gtl-client"
version = "0.1.0"
edition.workspace = true
rust-version.workspace = true
publish.workspace = true

[dependencies]
gtl-models.workspace = true
gtl-wire = { workspace = true, features = ["grpc"] }
thiserror.workspace = true
tonic.workspace = true

[target.'cfg(not(target_arch = "wasm32"))'.dependencies]
gtl-local-auth.workspace = true
tonic = { workspace = true, features = ["router", "transport"] }
tonic-health.workspace = true

[target.'cfg(target_arch = "wasm32")'.dependencies]
tonic-web-wasm-client = { workspace = true, optional = true }

[dev-dependencies]
tempfile.workspace = true
tokio = { workspace = true, features = [
  "macros",
  "net",
  "rt-multi-thread",
  "sync",
  "time",
] }
tokio-stream = { workspace = true, features = ["net"] }

[lints]
workspace = true

[features]
viewer-web = ["dep:tonic-web-wasm-client"]
