[package]
name = "dx-book"
version = "0.1.0"
edition.workspace = true
rust-version.workspace = true
publish.workspace = true

[features]
default = []
benchmark-support = []
catalog = [
  "csr",
  "dep:pulldown-cmark",
  "dioxus/document",
  "dioxus/hooks",
  "dioxus/router",
  "dioxus/signals",
]
csr = ["dep:web-sys", "dioxus/launch", "dioxus/web"]

[dependencies]
const_format = "0.2.36"
dioxus = { workspace = true, features = ["html", "macro"] }
dx-book-macros = { path = "macros" }
inventory = "0.3.24"
pulldown-cmark = { version = "0.13.4", default-features = false, features = [
  "html",
], optional = true }
web-sys = { workspace = true, features = ["Location"], optional = true }

[dev-dependencies]
dioxus = { workspace = true, features = ["lib"] }

[lints]
workspace = true
