export const TEST_IDS = {
  tabs: {
    strip: "tabs.strip",
    tab: "tabs.tab",
    nativeBadge: "tabs.native-badge",
    freshDot: "tabs.fresh-dot",
  },
  diffView: {
    root: "diff-view.root",
    titlebar: "diff-view.titlebar",
    keybar: "diff-view.keybar",
    toolbar: "diff-view.toolbar",
    layoutToggle: "diff-view.layout-toggle",
    layoutUnified: "diff-view.layout-unified",
    layoutSplit: "diff-view.layout-split",
    fullToggle: "diff-view.full-toggle",
    densityCompact: "diff-view.density-compact",
    densityFull: "diff-view.density-full",
    filter: "diff-view.filter",
    refresh: "diff-view.refresh",
    fileTree: "diff-view.file-tree",
    commitShelf: "diff-view.commit-shelf",
    content: "diff-view.content",
    fileList: "diff-view.file-list",
    filePanelMount: "diff-view.file-panel-mount",
    filePanel: "diff-view.file-panel",
    rowWindow: "diff-view.row-window",
    row: "diff-view.row",
    brokenSource: "diff-view.broken-source",
  },
  toast: {
    root: "toast.root",
    item: "toast.item",
  },
} as const;
