[package]
name = "gtl-web"
version = "0.1.0"
edition.workspace = true
publish.workspace = true

[dependencies]
dioxus = { workspace = true, features = ["lib"] }
dioxus-ssr = { version = "0.7.10", optional = true }
dioxus-sdk-time = "0.7.0"
dioxus-primitives = { git = "https://github.com/DioxusLabs/components", rev = "bf007c15d0cf4d04d3181cc46cf12325aa773955", version = "0.0.1", default-features = false }
dx-story = { workspace = true, optional = true }
futures-channel = { workspace = true, optional = true }
gtl-client = { workspace = true, optional = true, features = ["viewer-ipc"] }
gtl-models.workspace = true
gtl-wire.workspace = true
gtl-web-contracts.workspace = true
i18n-embed = { version = "0.16.0", features = ["fluent-system"] }
i18n-embed-fl = "0.10.1"
jiff.workspace = true
lru = { workspace = true, optional = true }
lucide-dioxus = { version = "3.26.0", features = [
  "account",
  "arrows",
  "development",
  "devices",
  "files",
  "layout",
  "notifications",
  "text",
  "time",
] }
serde.workspace = true
serde_json.workspace = true
wasm-bindgen.workspace = true
wasm-bindgen-futures.workspace = true
web-sys = { workspace = true, features = [
  "Clipboard",
  "ClipboardEvent",
  "CssStyleDeclaration",
  "DataTransfer",
  "Document",
  "DomRect",
  "Element",
  "HtmlDetailsElement",
  "HtmlDialogElement",
  "HtmlDocument",
  "HtmlElement",
  "HtmlTextAreaElement",
  "KeyboardEvent",
  "Location",
  "Navigator",
  "Node",
  "NodeList",
  "PointerEvent",
  "Range",
  "Selection",
  "Storage",
  "Window",
] }
thiserror = { workspace = true, optional = true }
unic-langid = { version = "0.9.6", features = ["macros"] }

[build-dependencies]
minifier = { version = "0.4.0", default-features = false, optional = true }

[dev-dependencies]
dioxus-ssr = "0.7.10"
fluent-syntax = "0.12.0"

[lints]
workspace = true

[features]
default = ["desktop"]
artifact = ["dep:dioxus-ssr", "dep:minifier", "dep:thiserror"]
component-preview = [
  "artifact",
  "dep:dx-story",
  "dx-story/catalog",
  "interactive-ui",
  "web",
]
desktop = [
  "interactive-ui",
  "web",
  "dioxus/router",
  "dep:gtl-client",
  "dep:futures-channel",
  "dep:lru",
]
interactive-ui = []
web = ["dioxus/launch", "dioxus/web"]

[[bin]]
name = "gtl-web"
path = "src/main.rs"
required-features = ["desktop"]

[[example]]
name = "component-preview"
path = "dev/main.rs"
required-features = ["component-preview"]
