syntax = "proto3";

package gtl.v1;

import "gtl/v1/viewer_theme.proto";

service SettingsService {
  rpc GetPushConfirmationRequirement(GetPushConfirmationRequirementRequest) returns (GetPushConfirmationRequirementResponse);
  rpc SetViewerTheme(SetViewerThemeRequest) returns (SetViewerThemeResponse);
}

message GetPushConfirmationRequirementRequest {}

message GetPushConfirmationRequirementResponse {
  bool push_confirmation_required = 1;
}

message SetViewerThemeRequest {
  ViewerTheme theme = 1;
}

message SetViewerThemeResponse {
  ViewerTheme theme = 1;
  string configuration_path = 2;
}
