[package]
name = "gtl-application"
version = "0.1.0"
edition.workspace = true
publish.workspace = true

[features]
testing = []

[dependencies]
anyhow.workspace = true
cqrsy.workspace = true
gtl-contracts.workspace = true
gtl-models.workspace = true
futures-util.workspace = true
natord.workspace = true
rusqlite.workspace = true
serde.workspace = true
semver.workspace = true
shlex.workspace = true
thiserror.workspace = true
tokio = { workspace = true, features = ["rt"] }
toml.workspace = true

[dev-dependencies]
strum.workspace = true
tokio = { workspace = true, features = ["macros"] }

[lints]
workspace = true
