[package]
name = "infra"
version = "0.1.0"
edition.workspace = true
publish.workspace = true

[[bench]]
name = "app_state"
harness = false

[dependencies]
anyhow.workspace = true
application.workspace = true
domain.workspace = true
jiff.workspace = true
parking_lot.workspace = true
rusqlite.workspace = true
rusqlite_migration.workspace = true
serde.workspace = true
serde_json.workspace = true
sha2.workspace = true
tempfile.workspace = true
tokio = { workspace = true, features = ["fs", "process"] }
toml.workspace = true
toml_edit.workspace = true
walkdir.workspace = true

[dev-dependencies]
criterion.workspace = true
gtl-platform.workspace = true
tokio = { workspace = true, features = ["fs", "macros", "rt"] }

[lints]
workspace = true
