[package]
name = "infra"
version = "0.1.0"
edition.workspace = true
publish.workspace = true

[dependencies]
anyhow.workspace = true
application.workspace = true
domain.workspace = true
jiff.workspace = true
maud.workspace = true
rusqlite.workspace = true
rusqlite_migration.workspace = true
serde.workspace = true
serde_json.workspace = true
sha2.workspace = true
similar.workspace = true
tempfile.workspace = true
tokio = { workspace = true, features = ["fs", "process"] }
toml.workspace = true
toml_edit.workspace = true
walkdir.workspace = true

[dev-dependencies]
gtl-platform.workspace = true
tokio = { workspace = true, features = ["fs", "macros", "rt"] }

[lints]
workspace = true
