//! Recolors the tray icon and the installed Linux launcher icon with the viewer theme.

#[cfg(target_os = "linux")]
mod launcher;

use gtl_wire::viewer::ViewerTheme;
use tauri::image::Image;

/// Identifies the tray icon so a theme change can replace its image.
pub(crate) const TRAY_ID: &str = "main";

/// The tray icon the shell shows before the viewer reports its theme.
pub(crate) const DEFAULT_TRAY_ICON: Image<'static> =
    tauri::include_image!("icons/themes/dark/tray.png");

/// One theme's icons, generated by `just desktop gen-icon`.
struct ThemeIcons {
    tray: Image<'static>,
    #[cfg_attr(not(target_os = "linux"), allow(dead_code))]
    launcher_svg: &'static [u8],
    #[cfg_attr(not(target_os = "linux"), allow(dead_code))]
    launcher_png: &'static [u8],
}

const fn theme_icons(theme: ViewerTheme) -> ThemeIcons {
    match theme {
        ViewerTheme::Dark => ThemeIcons {
            tray: DEFAULT_TRAY_ICON,
            launcher_svg: include_bytes!("../icons/themes/dark/launcher.svg"),
            launcher_png: include_bytes!("../icons/themes/dark/launcher.png"),
        },
        ViewerTheme::Mirage => ThemeIcons {
            tray: tauri::include_image!("icons/themes/mirage/tray.png"),
            launcher_svg: include_bytes!("../icons/themes/mirage/launcher.svg"),
            launcher_png: include_bytes!("../icons/themes/mirage/launcher.png"),
        },
        ViewerTheme::Glacier => ThemeIcons {
            tray: tauri::include_image!("icons/themes/glacier/tray.png"),
            launcher_svg: include_bytes!("../icons/themes/glacier/launcher.svg"),
            launcher_png: include_bytes!("../icons/themes/glacier/launcher.png"),
        },
        ViewerTheme::Graphite => ThemeIcons {
            tray: tauri::include_image!("icons/themes/graphite/tray.png"),
            launcher_svg: include_bytes!("../icons/themes/graphite/launcher.svg"),
            launcher_png: include_bytes!("../icons/themes/graphite/launcher.png"),
        },
        ViewerTheme::Carbon => ThemeIcons {
            tray: tauri::include_image!("icons/themes/carbon/tray.png"),
            launcher_svg: include_bytes!("../icons/themes/carbon/launcher.svg"),
            launcher_png: include_bytes!("../icons/themes/carbon/launcher.png"),
        },
    }
}

// Tauri's async command expansion contains `unreachable!`.
#[allow(clippy::unreachable)]
pub(crate) mod command {
    use gtl_client::ViewerClientError;
    use gtl_wire::viewer::ViewerTheme;
    use tauri::AppHandle;

    /// Draws the tray icon and any installed launcher icon in the viewer's theme.
    #[tauri::command]
    pub(crate) async fn desktop_theme_icons(
        app: AppHandle,
        request: ViewerTheme,
    ) -> Result<(), ViewerClientError> {
        let icons = super::theme_icons(request);
        #[cfg(target_os = "linux")]
        super::launcher::replace_installed(&app.config().identifier, &icons)
            .map_err(|error| ViewerClientError::desktop(&error))?;
        if let Some(tray) = app.tray_by_id(super::TRAY_ID) {
            tray.set_icon(Some(icons.tray))
                .map_err(|error| ViewerClientError::desktop(&error))?;
        }
        Ok(())
    }
}
