[package]
name = "gtl-server"
version = "0.1.0"
edition.workspace = true
rust-version.workspace = true
publish = false

[dependencies]
anyhow.workspace = true
gtl-application.workspace = true
gtl-artifacts.workspace = true
gtl-infra.workspace = true
gtl-local-auth.workspace = true
gtl-models.workspace = true
gtl-wire.workspace = true
tokio = { workspace = true, features = [
  "macros",
  "net",
  "rt-multi-thread",
  "signal",
  "sync",
  "time",
] }
tonic = { workspace = true, features = ["router", "transport"] }
tonic-health.workspace = true
tonic-reflection.workspace = true
tracing.workspace = true
tracing-subscriber.workspace = true

[dev-dependencies]
gtl-application = { workspace = true, features = ["testing"] }
prost.workspace = true
prost-types.workspace = true
tempfile.workspace = true
tokio-stream.workspace = true

[features]
benchmark-support = []

[lints]
workspace = true
