[package]
name = "gtl-server"
version = "0.1.0"
edition.workspace = true
publish = false

[dependencies]
anyhow.workspace = true
directories.workspace = true
gtl-application.workspace = true
gtl-artifacts.workspace = true
gtl-infra.workspace = true
gtl-local-transport.workspace = true
gtl-models.workspace = true
gtl-wire = { workspace = true, features = ["grpc"] }
clap.workspace = true
libc.workspace = true
prost.workspace = true
rolling-file.workspace = true
serde.workspace = true
serde_json.workspace = true
thiserror.workspace = true
tokio = { workspace = true, features = [
  "macros",
  "net",
  "rt-multi-thread",
  "signal",
  "sync",
  "time",
] }
tonic = { workspace = true, features = ["router", "transport"] }
tonic-health.workspace = true
tonic-reflection.workspace = true
tokio-stream.workspace = true
tower-http.workspace = true
tracing.workspace = true
tracing-appender.workspace = true
tracing-subscriber = { workspace = true, features = ["json"] }
uuid.workspace = true

[dev-dependencies]
gtl-client.workspace = true
gtl-application = { workspace = true, features = ["testing"] }
gtl-infra = { workspace = true, features = ["testing"] }
prost-types.workspace = true
serial_test.workspace = true
tempfile.workspace = true

[features]
benchmark-support = []

[lints]
workspace = true
