export {
  applyOpenedNativeTab,
  closeAllTabs,
  closeOthers,
  closeTabState,
  closeAllViewerTabs,
  closeOtherViewerTabs,
  closeViewerTabState,
  sortTabsByTime,
  sortViewerTabsByTime,
  type ApplyOpenedNativeTabResult,
  type Tab,
  type TabState,
  type ViewerTabState,
} from "./model/tab";
