proto = "crates/gtl-wire/proto/gtl/v1/settings.proto"
import-paths = ["crates/gtl-wire/proto"]
call = "gtl.v1.SettingsService.GetPushConfirmationRequirement"
total = 1020
skipFirst = 20
concurrency = 1
connections = 1
cpus = 1
insecure = true
timeout = "2s"
disable-template-data = true
data = {}
