[package]
name = "dx-book-cli"
version = "0.1.0"
edition.workspace = true
rust-version.workspace = true
publish.workspace = true

[[bin]]
name = "dx-book"
path = "src/main.rs"

[dependencies]
anyhow.workspace = true
cargo_metadata.workspace = true
clap.workspace = true
clap-cargo.workspace = true
command-group.workspace = true
serde.workspace = true
toml.workspace = true
walkdir.workspace = true

[dev-dependencies]
assert_cmd.workspace = true
predicates.workspace = true
tempfile.workspace = true

[lints]
workspace = true
